export const LOAD_DOCUMENT_BY_FIELD = "LOAD_DOCUMENT_BY_FIELD"
export const INSERT_DOCUMENT_COLLECTION = "INSERT_DOCUMENT_COLLECTION"
export const USERS_COLLECTION = "users"
export const EMAIL_PARAM = "email"